name: Cache build debug
on:
  push:
    branches: 
      - debug/docker-cache
jobs:
  Development-Deploy:
    permissions:
        id-token: write
        contents: read
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure OpenID Connect
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::363179374584:role/bookingly-dev-backend-oidc-debug-role
          aws-region: ${{ secrets.AWS_DEV_REGION }}

      - name: Check out code
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pull image
        run:  |
          docker pull 363179374584.dkr.ecr.eu-central-1.amazonaws.com/bookingly-dev-backend:latest
      
      - name: Get Tags for Image
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: "${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_DEV_REPOSITORY }}"
          tags: |
            type=raw,value=latest
            type=raw,value=main
            type=sha
      -
        name: Build, tag, and push docker image to Amazon ECR
        uses: docker/build-push-action@v3
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_DEV_REPOSITORY }}
        with:
          context: .
          file: Dockerfile.dev
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          build-contexts: booking="docker-image://363179374584.dkr.ecr.eu-central-1.amazonaws.com/bookingly-dev-backend:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
#       - name: Build, tag, and push docker image to Amazon ECR
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY: ${{ secrets.ECR_DEV_REPOSITORY }}
#         run: |
#           docker build --build-arg ENV_NAME='dev' --build-arg ENV_REGION='eu-central-1' -t $REGISTRY/$REPOSITORY:latest -t $REGISTRY/$REPOSITORY:${GITHUB_SHA::8} -f Dockerfile.dev .
#           docker push $REGISTRY/$REPOSITORY --all-tags
